### ISSUE TITLE
headers:false still outputs headers on Response

### ISSUE THREAD

**Issue by cheryl-c-tirerack** [anymaniax/orval#1056] opened 2023-11-15 20:02 UTC
## What are the steps to reproduce this issue?

1. in orval.config, for any mode, ie. 'tags'
2. set     output: {
      mode: 'tags',
      headers: false,

## What happens?
React-Query still shows headers 
…export const createPartner = (partner: BodyType<Partner>) => {
  return customInstance<Partner>({
    url: `/api/partners`,
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    data: partner,
  });
};

## What were you expecting to happen?
I do not want the tool to auto-generate the headers

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:**. Mac
**Package Version:** ^6.20.0
**Browser Version:** any

**Comment by melloware** [comment] 2023-11-15 20:31
I just tried it with 6.20.0 and can't reproduce.  Headers False does not create headers but headers:true does.  Please provide and exact reproducer.

**Comment by cheryl-c-tirerack** [comment] 2023-11-15 20:47
It is in propriety code and a large api. Can you share your config to produce no headers? Is mine in the right place? 
I will try to spin it up connecting to placeholder api.

**Comment by melloware** [comment] 2023-11-15 20:50
Sure it looks like this..

```js
module.exports = {
	nextfuse: {
		output: {
			target: "src/service/MyService.ts",
			client: "react-query",
			mock: false,
			prettier: false,
			headers: true,
			override: {
				useDates: false,
				mutator: {
					path: "src/service/AxiosMutator.ts",
					name: "useAxiosMutator",
				},
				query: {
					useQuery: true,
				},
			},
		},
		input: {
			target: "./openapi.json",
		},
	},
};
```

**Comment by cheryl-c-tirerack** [comment] 2023-11-15 21:28
Thank you for sharing config-just wanted to make sure I had mine in the right place.
Here is a minimum repo
https://github.com/cheryl-c-tirerack/orval-debug

See
api/partners/post.ts
The createPartner is giving a header that conflicts with other type definitions. My backend says that is not coming from the json, shown in repo above. 
Thanks for your time.

**Comment by melloware** [comment] 2023-11-15 21:34
Ohhh yours are `Response` output headers not `Request` input headers.  That is what that property currently controls.  Let me look.

**Comment by melloware** [comment] 2023-11-15 21:44
Wait these are the Content-Type headers to tell the server you want application-json?  Why do you want those excluded?

**Comment by cheryl-c-tirerack** [comment] 2023-11-15 21:50
I have headers set in my custom-instance, not shown in the reproduction.
If headers are set in my custom-instance has several, but the generated code does not show all of them, I get an eslint fail on build. It would be easier if all headers were controlled by my axios settings.

**Comment by melloware** [comment] 2023-11-15 21:52
Then I need a better example because that example above is working as expected?   And can't you just override the headers with an Axios Mutator?

**Comment by cheryl-c-tirerack** [comment] 2023-11-15 21:57
I've updated the example with my full custom-instance.
The headers here do not match the headers in the generated code and so I get eslint / typescript errors on build.
I have struggled a bit to understand this version of the axios instance vs interceptors and other methods I see online. So this could be a failure of understanding on my part. Everything worked perfectly until I hit an api endpoint that generates those for me.

**Comment by melloware** [comment] 2023-11-15 22:07
oh I have always used Interceptors to inject headers.

```js
import { AxiosInstance } from "axios";

/**
 * Axios utlity class for adding token handling and Date handling to all request/responses.
 */
export default class AxiosInterceptors {
	// hold instances of interceptor by their unique URL
	static requestInterceptors = new Map<string, number>();
	static responseInterceptors = new Map<string, number>();

	/**
	 * Configures Axios request/reponse interceptors to add JWT token.
	 *
	 * @param {AxiosInstance} instance the Axios instance to remove interceptors
	 * @param {string} apiKey the API Key to add to all Axios requests
	 * @param {string} apiUrl the API URL to add to all Axios requests
	 */
	static setupAxiosInstance = (instance: AxiosInstance, apiKey: string, apiUrl: string) => {
		const appKey = instance.defaults.baseURL!;
		EnvUtils.debug(`Configuring Axios request/response interceptors for: ${apiKey}`);
		// Axios request interceptor to add JWT token
		const tokenRequestInterceptor = instance.interceptors.request.use(
			(config) => {
				if (apiKey) {
					const headers = config.headers || {};
					headers["X-Domino-Api-Key"] = apiKey;
					headers["X-Domino-Api-Url"] = apiUrl;
				}
				return config;
			},
			(error) => {
				return Promise.reject(error);
			},
		);
		EnvUtils.debug(`Axios Token Request Interceptor: ${tokenRequestInterceptor}`);
		AxiosInterceptors.requestInterceptors.set(appKey, tokenRequestInterceptor);
	};

	/**
	 * Cleanup Axios on sign out of application.
	 *
	 * @param {AxiosInstance} instance the Axios instance to remove interceptors
	 */
	static teardownAxiosInstance = (instance: AxiosInstance) => {
		const appKey = instance.defaults.baseURL!;
		EnvUtils.warn(`Cleaning up Axios removing all interceptors for: ${appKey}`);
		instance.interceptors.request.clear();
		instance.interceptors.response.clear();
	};
}

```


Then use it like this setting it up once.

```js
AxiosInterceptors.setupAxiosInstance(AXIOS_INSTANCE, dominoApiKey, dominoApiInstance);
```

**Comment by melloware** [comment] 2023-11-16 01:03
Going to close this for now as not an Orval issue

**Closed by melloware** 2023-11-16 01:03 UTC
Labels: needs_reproducer

**Comment by cheryl-c-tirerack** [comment] 2023-11-17 13:57
Thank you for your help, I simplified my custom-instance and used interceptors properly and it is solved, so I appreciate the exchange.

**Comment by melloware** [comment] 2023-11-17 14:14
No problem!
