### ISSUE TITLE
Problem with ajv package since upgrading to orval 6.6.1

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#326] opened 2022-02-17 13:19 UTC
During the `npm install` execution I've got these notifications:
```
npm WARN @stoplight/better-ajv-errors@1.0.1 requires a peer of ajv@>=8 but none is installed. You must install peer dependencies 
yourself.
npm WARN ajv-errors@3.0.0 requires a peer of ajv@^8.0.1 but none is installed. You must install peer dependencies yourself.
```

Execution of `npx orval` command fails with an error:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
```

Installing the `ajv` package didn't fix the situation. I just got another error:
`Error compiling schema, function code: <LOTS_OF_CODE_HERE>`
```\node_modules\ajv\dist\compile\index.js:120
        throw e;
        ^

SyntaxError: Unexpected token ':'
    at new Function (<anonymous>)
    at Ajv.compileSchema (node_modules\@stoplight\spectral-core\node_modules\ajv\dist\compile\index.js:89:30)
```

**Comment by melloware** [comment] 2022-02-17 20:05
In your project or just trying to compile Orval ?  Orval uses `yarn` not `npm`.

However I am using Orval 6.6.1 in my `npm` project without issue?

**Comment by yekver** [comment] 2022-02-18 07:58
Yeah, I'm using it on project. Orval v. 6.6.0 works just fine.

>However I am using Orval 6.6.1 in my npm project without issue?
You may not face with this issue because of different orval configuration

**Comment by anymaniax** [comment] 2022-02-18 08:22
We updated some dependencies maybe that can cause the problem

**Comment by anymaniax** [comment] 2022-02-18 08:55
Could be a problem with the dependency `ibm-openapi-validator` that use `@stoplight/better-ajv-errors`

**Comment by anymaniax** [comment] 2022-02-18 09:03
From what I see in the lock file you should have that dependency

**Comment by anymaniax** [comment] 2022-02-18 09:05
which version of npm/node are you using?

**Comment by yekver** [comment] 2022-02-18 09:09
> which version of npm/node are you using?
```
npm v6.14.12
node v14.16.1
```

**Comment by anymaniax** [comment] 2022-02-18 09:16
I am not able to reproduce de problem 🙁

**Comment by yekver** [comment] 2022-02-18 10:11
Seems like this issue is linked to [this one](https://github.com/IBM/openapi-validator/issues/275)

**Comment by melloware** [comment] 2022-02-18 14:38
I am using...

**npm:** v8.0.0
**node:** v16.11.0

let us know if you figure it out. Oh also I am using just React Query.  My config is pretty straightforward.

```ts
module.exports = {
  authorization: {
    output: {
      mode: 'tags',
      target: 'src/service/openapi-auth/authorization.ts',
      client: 'react-query',
      mock: false,
      prettier: true,
      override: {
        useDates: true,
        mutator: {
          path: './src/service/AuthorizationMutator.ts',
          name: 'useAuthAxiosMutator',
        },
        query: {
          useQuery: true,
        }
```
      }
    },
    input: {
      target: './authorization-openapi.json',
    },
  },
};

**Comment by melloware** [comment] 2022-02-18 14:45
Yep looks like its fixed in [0.56.2](https://github.com/IBM/openapi-validator/releases/tag/ibm-openapi-validator%400.56.2) submitting a PR.

**Comment by anymaniax** [comment] 2022-02-20 09:44
Normally fixed with `6.6.3`

**Comment by yekver** [comment] 2022-02-21 09:43
Looks like the problem is caused by an `npm` because switching to `yarn` fixes the probled.

I have this errors by doing the `npm ls ajv` command:
```
+-- eslint@8.9.0
| +-- @eslint/eslintrc@1.1.0
| | `-- ajv@6.12.6  deduped
| `-- ajv@6.12.6
+-- fork-ts-checker-webpack-plugin@6.5.0
| `-- schema-utils@2.7.0
|   `-- ajv@6.12.6  deduped
+-- mini-css-extract-plugin@2.5.3
| `-- schema-utils@4.0.0
|   +-- ajv@8.10.0
|   `-- ajv-formats@2.1.1
|     `-- ajv@8.10.0
+-- orval@6.6.3
| `-- ibm-openapi-validator@0.57.0
|   +-- @ibm-cloud/openapi-ruleset@0.6.0
|   | +-- @stoplight/spectral-functions@1.5.1
|   | | `-- UNMET PEER DEPENDENCY ajv@8.10.0
|   | `-- @stoplight/spectral-rulesets@1.4.3
|   |   `-- UNMET PEER DEPENDENCY ajv@8.10.0
|   +-- @stoplight/spectral-cli@6.2.1
|   | `-- @stoplight/spectral-ruleset-migrator@1.7.2
|   |   `-- ajv@8.10.0
|   `-- @stoplight/spectral-core@1.10.1
|     `-- UNMET PEER DEPENDENCY ajv@8.10.0
+-- stylelint@14.5.1
| `-- table@6.8.0
|   `-- ajv@8.10.0
+-- webpack@5.69.1
| +-- schema-utils@3.1.1
| | `-- ajv@6.12.6  deduped
| `-- terser-webpack-plugin@5.3.1
|   `-- schema-utils@3.1.1
|     `-- ajv@6.12.6  deduped
`-- webpack-dev-server@4.7.4
  +-- schema-utils@4.0.0
  | `-- ajv@8.10.0
  `-- webpack-dev-middleware@5.3.1
    `-- schema-utils@4.0.0
      `-- ajv@8.10.0

npm ERR! peer dep missing: ajv@>=8, required by @stoplight/better-ajv-errors@1.0.1
npm ERR! peer dep missing: ajv@^8.0.1, required by ajv-errors@3.0.0
npm ERR! peer dep missing: ajv@>=8, required by @stoplight/better-ajv-errors@1.0.1
npm ERR! peer dep missing: ajv@>=8, required by @stoplight/better-ajv-errors@1.0.1
npm ERR! peer dep missing: ajv@^8.0.1, required by ajv-errors@3.0.0
```

**Comment by anymaniax** [comment] 2022-02-21 09:46
https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically

**Comment by yekver** [comment] 2022-02-21 10:59
I think we can close this issue in case I have no ability to upgrade `npm` to v7 and issue can be easily fix by switching to `yarn`

**Closed** 2022-02-21 11:25 UTC

**Comment by melloware** [comment] 2022-02-21 12:30
Which explains why I am not seeing it I am on NPM 8.

**Comment by yekver** [comment] 2022-02-22 09:43
JFYI: running `npm i -D ajv && npm dedupe` fixes the problem
