### ISSUE TITLE
How to pass axios options per query

### ISSUE THREAD

**Issue by yekver** [anymaniax/orval#282] opened 2021-12-15 15:53 UTC
I haven't found a possibility to add an `options` parameter for each generated query. From my point of view it shoul looks like this:

```javascript
const myApiCall = (queryParameter: string, options?: AxiosRequestConfig) => customAxiosInstance({ url: '/some_url', method: 'get', ...options })
```

There is a [similar issue](https://github.com/anymaniax/orval/issues/115) but I didn't get why there should be an extra parameter in mutator. From docs: 
> The second argument is only provided for the Angular client and give an instance of HttpClient

Also I tried to use an undocumented parameter `override.requestOptions` but had no luck :(

**Comment by anymaniax** [comment] 2021-12-15 15:57
Hey @yekver,  if you add a second argument to your mutator and regenerate. You should have what you want I think

**Comment by yekver** [comment] 2021-12-15 16:11
Yeah, that is exactly what I've done but have the same output. The thing I didn't get yet is why `override.requestOptions` is undocumented feature and why should I declare a second argument in my mutator (docs are telling that this argument is only for the Angular client, but I have React)?

**Comment by anymaniax** [comment] 2021-12-15 16:19
There is apparently a regression in the documentation. I will check that. But the requestOptions is to pass default options to your mutator and also if you want to add something at run time you can add a second argument to your mutator. Orval will try to read your mutator function to add the second argument to every query related to that mutator. Will check if there is a problem with all of that

**Comment by anymaniax** [comment] 2021-12-15 19:52
@yekver if you have the mutator warning that's why it doesn't work for you

**Comment by yekver** [comment] 2021-12-15 20:01
This is kind of a tricky thing 🙂

**Comment by anymaniax** [comment] 2021-12-15 20:03
Haha yes, you are in a weird case 😂

**Comment by yekver** [comment] 2021-12-16 12:55
You were right. In case custom mutator declaration file was parsed correctly I can finally see the `options` parameter in the generated query function call. But the typings are a bit strange. There is a type [SecondParameter](https://github.com/anymaniax/orval/blob/bb205cb7505fdcda5ccc206ad508842b73722c00/src/core/generators/axios.ts#L140-L146) which triggers lots of [@typescript-eslint/no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-explicit-any.md) lint errors.

The options parameter declared as: `options: SecondParameter<typeof customMutator>` I didn't get why don't you use a standart way like `options?: AxiosRequestConfig`? What is the point to define a second parameter in mutator function which will have the same meaning:

```javascript
export const customMutator<T>(config: AxiosRequestConfig, options?: AxiosRequestConfig) = {
  return Axios.create({ ...config, ...options })
}
```

**Comment by anymaniax** [comment] 2021-12-17 01:09
Because like that you can pass everything you want and not only an Axios type since you could use any other HTTP client

**Comment by anymaniax** [comment] 2022-02-20 09:45
can we close this issue?

**Comment by yekver** [comment] 2022-02-20 09:49
Yeah, I think the solution is described clearly.

**Closed** 2022-02-20 09:49 UTC
