### ISSUE TITLE
required with allOf doesn't work

### ISSUE THREAD

**Issue by lew** [anymaniax/orval#717] opened 2023-01-04 10:37 UTC
## What are the steps to reproduce this issue?

1. Take this minimal API:
```json
{
  "components": {
    "schemas": {
      "Example": {
        "properties": {
          "a": { "type": "number" },
          "b": { "type": "number" }
        },
        "type": "object"
      },
      "ExampleWithRequired": {
        "allOf": [
          { "$ref": "#/components/schemas/Example" },
          { "required": ["a"] }
        ],
        "type": "object"
      }
    }
  },
  "info": {
    "title": "required bug",
    "version": "1.0.0"
  },
  "openapi": "3.0.0",
  "paths": {
    "/example": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ExampleWithRequired" }
              }
            },
            "description": "OK"
          }
        }
      }
    }
  }
}
```

The "ExampleWithRequired" schema is defined using the "allOf" keyword, which allows you to combine multiple schemas into a single one. In this case, the "ExampleWithRequired" schema is a combination of the "Example" schema and an additional schema that has a "required" field set to an array containing "a". This means that the "ExampleWithRequired" schema describes an object that has the same properties as the "Example" object, but with the additional requirement that the "a" property must be present.

2. Generate the API.
3. Generated type contains `& unknown`
```ts
export interface Example {
  a?: number
  b?: number
}

export type ExampleWithRequired = Example & unknown
```

## What happens?
The resulting type contains the useless/wrong `& unknown`

## What were you expecting to happen?
A correct type according to JSON Schema standard should be generated

## Any logs, error output, etc?

…

## Any other comments?
Both    
![grafik](https://user-images.githubusercontent.com/42109/210535888-fb52fa6a-841a-47fb-b58f-2f56468b6bd3.png)

and     
![grafik](https://user-images.githubusercontent.com/42109/210535971-9653a0c7-df46-4db6-ba0e-e93862316e2a.png)

are valid definitions to require a referenced field
…

## What versions are you using?

**Operating System:** …
**Package Version:** 6.11.0-alpha.4
**Browser Version:** …

**Comment by mbaroukhcw** [comment] 2023-05-30 08:11
If you put the required outside of "allOf" : 
(I prefer to use yaml, it is shorter)

```yaml
openapi: 3.0.0
info:
  title: required bug
  version: 1.0.0
paths:
  /example:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleWithRequired'
          description: OK
components:
  schemas:
    Example:
      type: object
      properties:
        a:
          type: number
        b:
          type: number
    ExampleWithRequired:
      required:
        - a
      allOf:
        - $ref: '#/components/schemas/Example'
```

then it generate : 

```typescript
export interface Example {
  a?: number;
  b?: number;
}
export type ExampleWithRequired = Example;
```

which is wrong becase a should be mandatory.
BUT no more unknown.


To compare with 
```yaml
openapi: 3.0.0
info:
  title: required bug
  version: 1.0.0
paths:
  /example:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleWithRequired'
          description: OK
components:
  schemas:
    Example:
      type: object
      properties:
        a:
          type: number
        b:
          type: number
    ExampleWithRequired:
      allOf:
        - $ref: '#/components/schemas/Example'
        - required:
            - a
```

where it generates 
```typescript
export type ExampleWithRequired = Example & unknown;
```

**Comment by melloware** [comment] 2024-03-05 16:14
Isn't this a duplicate of #352 ?

**Closed by melloware** 2024-03-05 16:14 UTC
Labels: enhancement
