### ISSUE TITLE
Nothing Happens after Start

### ISSUE THREAD

**Issue by CollinHerber** [anymaniax/orval#868] opened 2023-05-21 21:27 UTC
## What are the steps to reproduce this issue?

I have the following config 
```js
module.exports = {
    api: {
        output: {
            workspace: "src/",
            schemas: "src/services/models",
        },
        input: {
            target: "https://qa.betsybot.xyz/betsyapi-qa/swagger/v1/swagger.json",
        },
    },
};
```
I run `npx orval@latest`

I get the following output 
```
> npx orval@latest

🍻 Start orval v6.15.0 - A swagger client generator for typescript
```
And nothing else. 

## What happens?

Nothing happens after starting

## What were you expecting to happen?

Models to be generated.

## Any logs, error output, etc?

N/A

## Any other comments?

Not really sure what else to add here.
Happy to answer any questions that come through.

I am running a AMD 5900x Processor

## What versions are you using?

**Operating System:** Window 10
**Package Version:** Orval @ Latest - Node @ v18.15.0
**Browser Version:** Chrome 113

**Comment by NimmLor** [comment] 2023-05-23 10:08
Hi, i did some investigations on this. Here is what I found out for now:
- The definition is loaded from the url correctly
- Same behaivour when using the same definition as a local file
- The [input transformer](https://orval.dev/reference/configuration/input#transformer) receives the openapi spec as expected

Could it be that there is a circular dependency somewhere? There is definitely some processing going on when looking into the task manager.

**Comment by anymaniax** [comment] 2023-05-24 07:26
I did an investigation yesterday night and found where is the problem in the code.  If you check [here](https://github.com/anymaniax/orval/blob/3ac8fe69b3cc1403d0b5658b5a4b13dfdf4e7320/packages/core/src/resolvers/value.ts#L30) I already tried to avoid that case but apparently in your case that doesn't work properly

**Comment by cody0203** [comment] 2023-06-21 04:10
Same here.
I downgraded to version 6.13.1 and it solved

**Comment by melloware** [comment] 2023-10-28 22:31
I think this is the same as #967

**Comment by melloware** [comment] 2023-11-03 18:02
Duplicate of https://github.com/anymaniax/orval/issues/967 so  I will leave that ticket open if you want to subscribe to that ticket.

**Closed by melloware** 2023-11-03 18:02 UTC
Labels: bug
