### ISSUE TITLE
File extension not applied to schemas generated files

### ISSUE THREAD

**Issue by MrLepage** [anymaniax/orval#1462] opened 2024-06-18 10:35 UTC
## What are the steps to reproduce this issue?

Add a file extension like `fileExtension: '.gen.ts'` to the `output`.

## What happens?

The defined `fileExtension` is not applied to the schemas generated files.

## What were you expecting to happen?

I would expect the schemas generated files to have the defined `fileExtension`

## Any other comments?

Any reason why the `fileExtension` is not applied to schemas generated files?

I have defined an eslint glob pattern to ignore generated files '**/*.gen.*' that cannot be applied to generated schemas files.

**Comment by melloware** [comment] 2024-06-18 11:20
This is a "good first issue" to investigate and fix.

**Comment by DanielVenable** [comment] 2024-06-19 02:42
I could try to work on this. Can you assign me?

**Comment by melloware** [comment] 2024-06-19 11:43
assigned to @DanielVenable

**Comment by DanielVenable** [comment] 2024-06-20 04:54
I am not able to reproduce this bug. I tried adding `fileExtension: '.gen.ts'` to `output` and it worked fine.

**Comment by MrLepage** [comment] 2024-06-20 05:45
In which mode?

**Comment by DanielVenable** [comment] 2024-06-20 17:23
I see the bug now. I will work on fixing it.

**Comment by DanielVenable** [comment] 2024-06-20 18:45
should the fileExtension be applied to index.ts?

**Comment by MrLepage** [comment] 2024-06-20 18:47
I'd like to say yes, it's still a file, so it should have the file extension defined.

**Closed** 2024-06-20 21:22 UTC
Labels: bug, good first issue
