### ISSUE TITLE
Producing an `unknown[]` type for an array field with `items` set to a type

### ISSUE THREAD

**Issue by lmossman** [anymaniax/orval#726] opened 2023-01-10 04:43 UTC
## What are the steps to reproduce this issue?

1. Clone my orval-example repo: https://github.com/lmossman/orval-example
2. Run `npm install` then `npm run orval`
3. See that the `Client.ts` file produced has an `unknown[]` type, which is unexpected: https://github.com/lmossman/orval-example/blob/c460c310267f03311e00dda5a2f1394c2db4a839/src/client/Client.ts#L25

## What happens?

The `fields` field has its type set to `unknown[]`

## What were you expecting to happen?

The type of `fields` should be `AddedFieldDefinition[]` instead of `unknown[]`

## Any logs, error output, etc?
It doesn't seem related, but this is printed out for the repro instructions I listed above. These same logs aren't printed out for my production repo though, so my guess is these are coming from me trying to just pull a sample of the schema out for the example
```
⚠️  SyntaxError: Swagger schema validation failed.
  #/paths/~1transformations/get/responses/200/content/application~1json/schema must NOT have additional properties
  #/paths/~1transformations/get/responses/200/content/application~1json/schema must NOT have additional properties
  #/paths/~1transformations/get/responses/200/content/application~1json/schema must NOT have additional properties
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields/properties/fields/items must be object
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields/properties/fields/items must be object
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields/properties/fields/items must match exactly one schema in oneOf
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields/properties/fields must have required property '$ref'
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields/properties/fields must match exactly one schema in oneOf
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields must have required property '$ref'
  #/paths/~1transformations/get/responses/200/content/application~1json/schema/properties/add_fields must match exactly one schema in oneOf
  #/paths/~1transformations/get/responses/200/content/application~1json/schema must have required property '$ref'
  #/paths/~1transformations/get/responses/200/content/application~1json/schema must match exactly one schema in oneOf
  #/paths/~1transformations/get/responses/200 must have required property '$ref'
  #/paths/~1transformations/get/responses/200 must match exactly one schema in oneOf
```

## Any other comments?

My guess is that orval has trouble with an array field when `items` is set to a `$ref` - it seems like it loses the type when that happens and defaults to setting the type of the array to `unknown`

## What versions are you using?

**Operating System:** macOS 12.5
**Package Version:** 6.11.0
**Browser Version:** Chrome 108.0.5359.124

**Comment by lmossman** [comment] 2023-01-13 19:53
@anymaniax I just noticed that this is actually also happening for a json schema array whose `items` field is _not_ set to a ref, e.g.
```
    properties:
      array_field:
        type: array
        items:
          - type: string
```
causes orval to produce a `array_field: unknown[]` instead of `array_field: string[]`

**Comment by arthurfiorette** [comment] 2023-02-10 13:44
same here

**Comment by melloware** [comment] 2023-11-10 03:13
Can you confirm this is still happening with 6.20.0 ?

**Comment by arthurfiorette** [comment] 2024-01-03 12:28
It's not happening for us anymore... However our schema has changed a lot since and as no reproduction repository was made, you can close this issue until further notice.

**Closed** 2024-01-03 12:35 UTC
Labels: bug
