### ISSUE TITLE
Question: What's the recommended way to use the generated infinite queries?

### ISSUE THREAD

**Issue by fbinz** [anymaniax/orval#917] opened 2023-08-21 07:08 UTC
First, I want to thank you for making this great tool! It has saved me a great deal of time and makes coordinating my backend and my frontend almost effortless.

However, I'm wondering if there is a better way to use the generated infinite queries.
Currently, I do the following:

```typescript

export const useSomeResourceWrapped: typeof useResourceInfinite<PaginatedResponseResourceOut> = (options) => {
  const { query } = options || {};

  return useResourceInfinite<PaginatedResponseResourceOut>({
    query: {
      getNextPageParam: ({ next, results }) =>
        !!results && next ? next : undefined,
      ...query,
    },
  });
};
```
`useResourceInfinite` is the generated query from orval. I'm building my API such that the `getNextPageParam` function is always the same (i.e. it has a `next` and a `results` attribute).

How could I avoid wrapping the generated infinite query everytime just to set the same `getNextPageParam` function again?
Is there a recommended way to do so (i.e. write some generic wrapper)?

**Comment by melloware** [comment] 2023-11-10 03:01
Duplicate of #708

**Closed** 2023-11-10 03:01 UTC
Labels: question

**Comment by camhammel** [comment] 2024-06-17 17:54
> Duplicate of #708

While they're slightly related, it doesn't seem to me that they're the same issue:
> I'm building my API such that the getNextPageParam function is always the same (i.e. it has a next and a results attribute). How could I avoid wrapping the generated infinite query everytime just to set the same getNextPageParam function again?

This is something that I think warrants being looked at separately - I can't imagine having the same pagination strategy across multiple endpoints would be uncommon, and accounting for that in a more global setting would reduce a lot of boilerplate when using these generated queries
