### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by kubakl** [anymaniax/orval#513] opened 2022-07-27 10:25 UTC
## What are the steps to reproduce this issue?

1. Write a config for react-query as the client
2. Run orval command (v6.9.2

## What happens?
A weird error appears, don't even know what's the issue
…

## What were you expecting to happen?
Generate the models and API operations for all the enpoints
…

## Any logs, error output, etc?
petstore - TypeError: Cannot read properties of undefined (reading 'slice')
…

## Any other comments?
I saw there's already an issue which is really similar https://github.com/anymaniax/orval/issues/494
…

## What versions are you using?

**Operating System:** MacOS X (M1)
**Package Version:** v6.9.2
**Browser Version:** …

**Comment by anymaniax** [comment] 2022-07-30 08:55
Hello @kubakl do you have an example for me?

**Comment by kubakl** [comment] 2022-07-30 11:20
@anymaniax What type of example you want me to give you? The OpenAPIi spec?

**Comment by anymaniax** [comment] 2022-07-30 11:35
If you can yes

**Comment by kubakl** [comment] 2022-08-14 14:59
Sorry for not answering, I assume it's a config issue, I copied it from the documentation but still it may be wrong:
```javascript
module.exports = {
  petstore: {
    output: {
      mode: 'tags-split',
      target: 'src/petstore.ts',
      schemas: 'src/model',
      client: 'react-query',
      mock: true,
    },
    input: {
      target: '../schema/api-v1.yaml',
    },
  },
};
```
The schema doesn't have any issues because I also generate golang code using openapi-generator and it works just fine.

**Comment by anymaniax** [comment] 2022-08-15 09:58
Hi @kubakl, I would need the yaml or an example that reproduce the error with the yaml

**Comment by lmossman** [comment] 2022-10-19 19:11
@anymaniax I'm reviving this thread as I am running into the same issue with orval printing out 
```
🛑  api - TypeError: Cannot read properties of undefined (reading 'slice')
```

I have created a repo with a simple example that can be used to reproduce this error: https://github.com/lmossman/orval-example

To reproduce the error, you can follow these steps:
1. `git clone git@github.com:lmossman/orval-example.git`
2. `cd orval-example`
3. `npm install`
4. `npm run orval`
which will output the error above.

I believe this error happens when trying to reference an external json/yaml file in the OpenAPI spec, like I do on this line that I added to your `petstore.yaml` sample file:
https://github.com/lmossman/orval-example/blob/a8c46736987cf2ffd3fd3b7bf6f50048937000b4/src/petstore.yaml#L116-L117

I have confirmed that the `openapi-generator` validates my OpenAPI spec successfully, and is able to produce client code from it. So this issue seems to be specific to orval not being able to handle referencing external files.

Let me know if there is any other info that I can provide here! I'd love to get this fixed as we need to be able to reference external files in our production application that is using orval. Thanks!

**Comment by kubakl** [comment] 2022-10-20 11:31
As @lmossman says, I also have the same structure in my OpenAPI definition, I split it across different files, paths, schemas, responses etc. This actually could be the problem.

**Comment by hbarrientosg** [comment] 2022-10-31 15:30
As temporary solution you could generate your schema with openapi-cli and then use orval with the output.
```
openapi-cli bundle yourschema.yaml -o tmp/yourschema.json && orval --config orval.config.ts --clean
```
On your orval you should add the generated file.
```
...
    input: {
      target: resolve(__dirname, "./tmp/yourschema.json"),
    },
...
```

**Comment by lmossman** [comment] 2022-11-03 18:50
@hbarrientosg nice suggestion, I will try that! Thanks

**Comment by anymaniax** [comment] 2022-11-03 20:40
Hello @lmossman, @hbarrientosg, @kubakl, I improved the parsing and everything should work as expected in the next release

**Comment by lmossman** [comment] 2022-11-19 00:45
@anymaniax I have upgraded to version `6.11.0-alpha.5` of orval, and while I no longer get the `TypeError` posted above, the generated typescript still doesn't seem quite right.

For components that are pointing to external JSON schema files, the typescript file that orval generates still doesn't contain classes for the referenced JSON. It just adds a type onto the field which is the capitalized version of the field name, but doesn't actually define what that type is.

For example, in my [orval-example repo](https://github.com/lmossman/orval-example) that I created to demonstrate this behavior, I point to a breed.json JSON schema file here with a $ref: https://github.com/lmossman/orval-example/blob/ae07d4565f2851a86b211240e92259a5bfa1994d/src/petstore.yaml#L116-L117

But when I run `npm run orval`, the `Petstore.ts` file it generates just contains this interface definition for Pet, without ever defining the interface for Breed: https://github.com/lmossman/orval-example/blob/ae07d4565f2851a86b211240e92259a5bfa1994d/src/client/Petstore.ts#L29

So pointing to an external file results in broken typescript code generated from orval.

**Comment by anymaniax** [comment] 2022-11-20 12:57
@lmossman can you try `6.11.0-alpha.6` and tell if it's good for you now?

**Comment by lmossman** [comment] 2022-11-21 18:38
@anymaniax it is a bit closer now, but I still have a couple of issues:
1. If the external JSON schema file is in some nested path, then orval uses two different names for the generated type. 
For example, [here](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/petstore.yaml#L116-L117) I am now pointing to a nested directory that contains the JSON schema, and this results in orval generating the `Pet` object with a `breed` field of [type Breed](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/client/Petstore.ts#L30), but it defines that type with the name [PathToSchemaBreed](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/client/Petstore.ts#L9-L12)
2. It seems that orval is only generating types for the top-level fields in the external JSON schema, whereas I need it to generate types for every field and every nested field in that JSON schema.
For example, [here](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/petstore_nested_json.yaml#L116-L117) I point to an external JSON schema file which contains a [definitions block](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/path/to/schema/breed_nested.json#L17), containing JSON schema blocks that are pointed at with `$ref` in other parts of the file. This does produce an output file, but it only defines  the top-level [PathToSchemaBreedNested type](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/client/PetstoreNestedJson.ts#L9-L13), and doesn't define types for nested fields like [Ancestry](https://github.com/lmossman/orval-example/blob/a20f43b966e839fa9cc55c30b62bd47772a4aa80/src/client/PetstoreNestedJson.ts#L12). Orval also prints out these warnings when I run orval on that file:
```
🍻 Start orval v6.11.0-alpha.6 - A swagger client generator for typescript
🎉 api - Your OpenAPI spec has been converted into ready to use orval!
⚠️  SyntaxError: Swagger schema validation failed.
  #/paths/~1pets/get/responses/200/content/application~1json/schema/items/properties/breed must NOT have additional properties
  #/paths/~1pets/get/responses/200/content/application~1json/schema/items/properties/breed must have required property '$ref'
  #/paths/~1pets/get/responses/200/content/application~1json/schema/items/properties/breed must match exactly one schema in oneOf
  #/paths/~1pets/get/responses/200/content/application~1json/schema/items must have required property '$ref'
  #/paths/~1pets/get/responses/200/content/application~1json/schema/items must match exactly one schema in oneOf
  #/paths/~1pets/get/responses/200/content/application~1json/schema must have required property '$ref'
  #/paths/~1pets/get/responses/200/content/application~1json/schema must match exactly one schema in oneOf
  #/paths/~1pets/get/responses/200 must have required property '$ref'
  #/paths/~1pets/get/responses/200 must match exactly one schema in oneOf
  #/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema/properties/breed must NOT have additional properties
  #/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema/properties/breed must have required property '$ref'
  #/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema/properties/breed must match exactly one schema in oneOf
  #/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema must have required property '$ref'
  #/paths/~1pets~1{petId}/get/responses/200/content/application~1json/schema must match exactly one schema in oneOf
  #/paths/~1pets~1{petId}/get/responses/200 must have required property '$ref'
  #/paths/~1pets~1{petId}/get/responses/200 must match exactly one schema in oneOf
  #/components/schemas/Pet/properties/breed must NOT have additional properties
  #/components/schemas/Pet/properties/breed must have required property '$ref'
  #/components/schemas/Pet/properties/breed must match exactly one schema in oneOf
  #/components/schemas/Pet must have required property '$ref'
  #/components/schemas/Pet must match exactly one schema in oneOf
  #/components/schemas/Pets/items/properties/breed must NOT have additional properties
  #/components/schemas/Pets/items/properties/breed must have required property '$ref'
  #/components/schemas/Pets/items/properties/breed must match exactly one schema in oneOf
  #/components/schemas/Pets/items must have required property '$ref'
  #/components/schemas/Pets/items must match exactly one schema in oneOf
  #/components/schemas/Pets must have required property '$ref'
  #/components/schemas/Pets must match exactly one schema in oneOf

🎉 apiNestedJson - Your OpenAPI spec has been converted into ready to use orval!
```

If orval can correctly produce an output file for that [petstore_nested_json.yaml](https://github.com/lmossman/orval-example/blob/main/src/petstore_nested_json.yaml) spec which contains properly-named types for `Breed`, `Ancestry`, and `OriginLocation`, that would be perfect! Thanks

**Comment by anymaniax** [comment] 2022-11-24 13:38
@lmossman I fixed the two issues but still have a little problem with the relative path. Will try to fix it asap to be able to release a new alpha with it

**Comment by lmossman** [comment] 2022-11-30 00:26
@anymaniax I tried this out and it seems to have fixed most of the issues I was seeing. However, when I tried this out in the actual project I am using orval for, I still ran into a case where a typescript type did not properly get generated for a definition in the JSON file.

I have updated my example [here](https://github.com/lmossman/orval-example) to demonstrate this issue. Notice that if you run `npm run orval` on that repo's current master, the `Petstore.ts` file that it generates does not contain a type definition for [JsonSchema](https://github.com/lmossman/orval-example/blob/c547cb7aa31d5723dc81b79eb37453e3d5eb0aab/src/client/Petstore.ts#L63) or [SimpleRetriever](https://github.com/lmossman/orval-example/blob/c547cb7aa31d5723dc81b79eb37453e3d5eb0aab/src/client/Petstore.ts#L64).

I think this may be an issue with `allOf` in the JSON schema - having this field in an object seems to cause orval to not generate a type for it.

**Comment by anymaniax** [comment] 2022-11-30 09:58
@lmossman can you try with `orval@6.11.0-alpha.9`

**Comment by lmossman** [comment] 2022-11-30 18:36
@anymaniax thanks for the quick response! This is looking really close, but I found one more issue: it seems that two duplicate typescript types with the same name are being generated in the case that there are two fields with almost the same name (only a `_` prefix differentiates them).

I've updated my repo here with an example of this: the DeclarativeStream definition in my JSON schema has a [schema_loader and a _schema_loader](https://github.com/lmossman/orval-example/blob/bfd21a2bca95d7541bcf69071b0ad88407aaeb19/src/path/to/schema/config_component_schema.json#L38-L57) field each with the same `anyOf` value, and this causes orval to generate [two identical  DeclarativeStreamSchemaLoader types](https://github.com/lmossman/orval-example/blob/bfd21a2bca95d7541bcf69071b0ad88407aaeb19/src/client/Petstore.ts#L140-L146), which is not allowed since it is a duplicate identifier.

**Comment by kubakl** [comment] 2022-12-02 15:27
Now it works for me with no problems, thx very much!

**Comment by lmossman** [comment] 2022-12-05 22:09
@anymaniax is it looking like the issue I described [above](https://github.com/anymaniax/orval/issues/513#issuecomment-1332578436) is a straightforward fix? I think this is the last issue that is blocking me from using orval in our production app so I'm really looking forward it being resolved!

**Comment by anymaniax** [comment] 2022-12-06 11:53
@lmossman  you can try with `6.11.0-alpha.10` should be fixed

**Comment by lmossman** [comment] 2022-12-06 23:09
@anymaniax that seems to have fixed it! Thank you for the quick response. I believe all of the issues called out in this thread have been resolved in the latest version, so this issue can be resolved

**Comment by anymaniax** [comment] 2022-12-07 07:47
@lmossman cool don’t hesitate if you have other issues

**Closed** 2022-12-07 07:47 UTC
Labels: bug

**Comment by lmossman** [comment] 2023-01-11 22:49
FYI @anymaniax I discovered another problem, so I opened an issue here: https://github.com/anymaniax/orval/issues/726
