### ISSUE TITLE
Vue: Data not (re)fetched when computed parameter changed

### ISSUE THREAD

**Issue by paulgovers** [anymaniax/orval#849] opened 2023-05-04 08:44 UTC
## What are the steps to reproduce this issue?
when using the following setup:
const customernumberComputed = computed(() => {
  return customernumber.value ? { customernumber: customernumber.value } : undefined;
});

const {
  data: productsData,
  isLoading,
  queryKey
} = useProductsGetByCustomerNumber(customernumberComputed .value, {
  query: { select: result => result.result ?? [] }
});

data is not re-fetched when customernumber changed.
only when the component is mounted, the data is being fetched

## What happens?

data is not re-fetched when customernumber changed, it seems working not reactive

## What were you expecting to happen?

an api call will be executed when customernumber changes

## What versions are you using?

**Operating System:** Windows
**Package Version:** Orval 6.13.1, Vue3
**Browser Version:** latest Chome version

**Comment by AlmarAubel** [comment] 2023-05-20 13:30
I think this is fixed by implementing the vue reactive pattern see #851

**Comment by melloware** [comment] 2023-11-29 00:11
Duplicate of #851

**Closed** 2023-11-29 00:11 UTC
Labels: duplicate
