### ISSUE TITLE
TanStack react query v5 marks `queryKey` as required

### ISSUE THREAD

**Issue by leniency** [anymaniax/orval#975] opened 2023-10-20 18:11 UTC
This makes adding additional query options annoying as it forces overriding the query key that gets set in the generated code.

This only appears to affect queries and not mutations.

**Comment by melloware** [comment] 2023-10-24 17:20
This was released in 6.19.1 can you test @leniency please?

**Closed by melloware** 2023-10-24 17:20 UTC
Labels: bug

**Comment by leniency** [comment] 2023-10-25 15:51
Yup all good now, thanks!

**Comment by ruiaraujo012** [comment] 2024-01-04 14:35
Still happens, any fix?

**Comment by melloware** [comment] 2024-01-04 14:55
Not many changes since 6.22.1 so look through the commits and see if you can spot it: https://github.com/anymaniax/orval/compare/v6.22.1...master

**Comment by ruiaraujo012** [comment] 2024-01-04 15:03
The genereted code is different
```ts
(6.30.0) query?: UseQueryOptions<Awaited<ReturnType<typeof getDomainValues>>, TError, TData>;
(6.22.1) query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainValues>>, TError, TData>>;
```

**Comment by melloware** [comment] 2024-01-04 15:17
@anymaniax I don't see any commit between 6.22.1 and 6.23.0 that would affect this `Partial` not being generated?  @Maxim-Mazurok @codebutler @soartec-lab

**Comment by soartec-lab** [comment] 2024-01-04 15:43
@melloware 

So you want to know the reason why `Partial` is no longer generated?
if me question is correct, I'll search into it. and, I will also make corrections if possible.

I also read [this](https://github.com/anymaniax/orval/issues/899) as well.

**Comment by melloware** [comment] 2024-01-04 16:15
Yes I don't see what changed that would cause this between 6.22.1 and 6.23.0.

**Comment by soartec-lab** [comment] 2024-01-05 01:39
@maapteh @ruiaraujo012 

Hi, I checked the operation using `PetStore`, and the source code was generated with `Partial` existing as intended.

```
export const getListPetsQueryOptions = <TData = Awaited<ReturnType<typeof listPets>>, TError = AxiosError<Error>>(params?: ListPetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {
```

using `orval` version is bellow:

```
$ npm list --depth=0 | grep orval
+-- orval@6.23.0
```

I also checked the source code, but could not find any part that would reproduce the problem.
If possible, could you please share the minimal OpenAPI definition file?

**Comment by soartec-lab** [comment] 2024-01-05 01:40
@maapteh @ruiaraujo012 @melloware 

Hi, I checked the operation using `PetStore`, and the source code was generated with `Partial` existing as intended.

```
export const getListPetsQueryOptions = <TData = Awaited<ReturnType<typeof listPets>>, TError = AxiosError<Error>>(params?: ListPetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {
```

using `orval` version is bellow:

```
$ npm list --depth=0 | grep orval
+-- orval@6.23.0
```

I also checked the source code, but could not find any part that would reproduce the problem.
If possible, could you please share the minimal OpenAPI definition file?

**Comment by ruiaraujo012** [comment] 2024-01-05 08:52
You're right, I tried again with v6.23.0, and it worked, it created the Partial.
I don't know what happened here, but it's working. Sorry for wasting your time.

**Comment by soartec-lab** [comment] 2024-01-05 08:56
@ruiaraujo012 
it's okay. thank you for retry. I'm glad it went well 🙌

**Comment by maapteh** [comment] 2024-01-05 08:56
I thought this would be an easy one. But not. When i isolate the package from my pnpm monorepo and only install what is used in the setup for this generating and just use my own open-api yaml and the petstore yaml from your codebase i do see the Partial. 

https://github.com/maapteh/orval-maybe-bug/blob/main/src/api/index.ts#L159
so there it is correct :(

**Comment by soartec-lab** [comment] 2024-01-05 09:03
@maapteh 

Thank you for checking too.
Is it okay to conclude that this is not a bug and end the discussion on this issue? And if you have any problems, could you open a new issue by sharing your OpenAPI definition and generated codebase?

**Comment by maapteh** [comment] 2024-01-05 09:17
Yes i will ask some extra eyes in our monorepo, the weird thing is that when i run pnpm why i do see the correct versions :(

**Comment by maapteh** [comment] 2024-01-05 11:54
found the cullprit.

```
  const hasQueryV5 = true /* query.version === 5 || isQueryV5(
    context.packageJson,
    outputClient
  ); */
  ```
  
  The V5 version detection was always false. When i override it to true i saw the Partial. Now i have to look why in a pnpm monorepo it cant not find the correct version which has been set in the workspace root.

**Comment by maapteh** [comment] 2024-01-05 13:44
Created at #1144

**Comment by tlrobinson** [comment] 2024-04-16 20:08
I had the same issue when running Orval in a npm workspace that had react-query as a peerDependency. It would be nice if it correctly detected that.

**Comment by anymaniax** [comment] 2024-04-16 22:13
@tlrobinson you can specify which version you want in the config too now

**Comment by NielsCodes** [comment] 2024-04-17 09:49
> @tlrobinson you can specify which version you want in the config too now
Could you show an example? I don't see this version option mentioned anywhere in the docs or examples.

I am facing the same issue. I have a PNPM Workspace, which uses Orval to generate the hooks for my frontend package based on the OpenAPI spec of the backend package. Since the generation runs on the Workspace level and not in my frontend package itself, I assume this version check is failing.

**Comment by anymaniax** [comment] 2024-04-17 11:04
something like this

```ts
 module.exports = {
   petstore: {
     output: {
       ...
       override: {
         query: {
           version: the version you want
         },
       },
     },
     ...
   },
 };
```
